### ISSUE TITLE
** Error: (TileGrid): cannot load "resource/maps/playfield_1.rnc"

### ISSUE THREAD

**Issue by agentbooth** [jotd666/bagman#5]
I tried compiling this on linux but after hitting Ctrl to start the game on the title screen, I get the following error during run-time:
`** Error: (TileGrid): cannot load "resource/maps/playfield_1.rnc"`

Are there some additional .rnc files missing from the github?

**Comment by jotd666** [comment]
Oh sorry those weren't tracked! this is now fixed

**Comment by jotd666** [comment]
[fixed](https://github.com/jotd666/bagman)

**Comment by agentbooth** [comment]
ok great, thanks!
